<?php
return [
  'draggable' => true,
  'hidden' => false,
  'uploadzoneclass' => 'uploadzone',
  'acceptable_mimes' => 'png,jpg,jpeg,gif,doc,rtf,docx,doc,pdf,txt,htm,html,odt,ogg,mp3,aac,raw,flac,au,zip,gz,xls,ods,csv,ppt,odp,avi,mov,mpg,mpeg,mpa,asf,wma,mp2',
  'droptext' => '#uploader::messages.droptext#',
  'divclass' => 'form-row',
  'divcol' => 'form-group col-md-2',
  'labelclass' => '',
  'buttonclass' => 'btn btn-dark',
  'uploadicon' => "fas fa-upload",
  'uploadtext' => "#uploader::messages.uploadtext#",
  'progbarmainclass' => "progress",
  'progressbarwidth' => '40%',
  "progressbar" => "progress-bar progress-bar-striped progress-bar-animated",
  'failmessage' => "#uploader::messages.failmessage#",
  'alerterrorclass' => 'alert alert-danger',
  'alertsuccessclass' => 'alert alert-success',
  'alerttimeout' => 10000,
  'defaultpath' => "/",
  'resultclass' => 'UploadresultProcessor',
  'errorfn' => null,
  'buildresultdivfn' => 'builduploadresultdiv',
  'maxfilesizek' => null,
];
